image: python:3.7.2
pipelines:
  default:
    - step:
        script:
          - pip install -r requirements.txt
          - cd sample
          - python manage.py test
          - python manage.py migrate
          - python manage.py runserver